### PR TITLE
grafana: initial version of dashboards in YAML

### PR DESCRIPTION
**Pull request by sodar**
- `grafyaml` does not support `table` as panel type as of yet

### CODE REVIEW

**Comment by krdln** [comment]
I wonder if it's possible to get rid of this duplication here. Would be nice to do it, but I don't have any clear ideas on how.

Also, I see that you didn't add the `$Status` and `$Job` variables. I felt like quickly filtering by failed jobs was a nice feature. Also, if we used `$Job` variable, we could have just one dashboard, and access it by different urls based on `prod`/`devel`.

**Comment by sodar** [comment]
@krdln I agree, we need to deduplicate the code in future. There is some templating support in `grafyaml`, but I did not figure it out yet. Same with `$Status` and `$Job` variable.

**Comment by krdln** [comment]
You're using `AND status in ($Status)` only in one of the graphs. Is this on purpose?

**Comment by sodar** [comment]
I forgot about the rest. I will add them.

**Pull request merged**
