### PR TITLE
WIP: Try collecting logs from stopped containers.

### PR DESCRIPTION
**Pull request by m-kostrzewa**

### CODE REVIEW

**Comment by m-kostrzewa** [comment]
recheck no bug

**Comment by m-kostrzewa** [comment]
recheck no bug

**Comment by m-kostrzewa** [comment]
recheck no bug

**Comment by m-kostrzewa** [comment]
recheck no bug

**Comment by jacekchalupka** [comment]
m-kostrzewa left the team, without telling anyone what this PR is about.

**Pull request closed without merging**
