### PR TITLE
Fix typo in flakes/README.md

### PR DESCRIPTION
**Pull request by m-kostrzewa**

### CODE REVIEW

**Comment by krdln** [comment]
huh? http://logs.opencontrail.org/winci/github/WinContrail/contrail-win-ci-gh/2264/SUSPECTED-ERROR-HERE-log.build.txt.gz#_2018-08-30_11_36_09_548000

**Comment by krdln** [comment]
recheck no bug

**Comment by m-kostrzewa** [comment]
@krdln wut?

**Comment by sodar** [comment]
@krdln Builder node did not have the `GOROOT` environment variable set. This node was a victim of last disk failure and was offline for a few days. Decided to remove it and provision a new one.

**Pull request merged**
