### PR TITLE
DO NOT MERGE Save vhost address after starting all of services

### PR DESCRIPTION
**Pull request by mzaremba04**

### CODE REVIEW

**Comment by mzaremba04** [comment]
recheck no bug

**Comment by mzaremba04** [comment]
recheck no bug

**Comment by jacekchalupka** [comment]
recheck no bug

**Comment by jacekchalupka** [comment]
recheck no bug

**Comment by jacekchalupka** [comment]
recheck no bug

**Comment by jacekchalupka** [comment]
recheck no bug

**Comment by jacekchalupka** [comment]
Merged in other PR.

**Pull request closed without merging**
