### PR TITLE
logs: move SconsTestLogs to unittest-logs; index.html in pretty_test_report

### PR DESCRIPTION
**Pull request by sodar**

### CODE REVIEW

**Comment by sodar** [comment]
Note to self:

- might be useful to extract testenv provisioning logs to a separate file
- pipeline stage logs can be extracted but length is limited by a configurable property in Jenkins plugin
    - log extracting example: https://gist.github.com/sodar/ba1cd102ad79fceddbc2bf835198d686
- property in question is `com.cloudbees.workflow.rest.external.FlowNodeLogExt.maxReturnChars`
    - configurable with `init.groovy` files
    - example: https://github.com/rancher/pipeline-jenkins-server/blob/0e4e1044a3e389784d68a1d9c66848b7a5f905c2/init.groovy

**Comment by sodar** [comment]
recheck no bug

**Comment by sodar** [comment]
recheck no bug

**Comment by jablonskim** [comment]
recheck no bug

**Pull request merged**
