### PR TITLE
Use template CentoOS 7.5

### PR DESCRIPTION
**Pull request by pmarcinkiewicz1**

### CODE REVIEW

**Comment by sodar** [comment]
recheck no bug

**Comment by sodar** [comment]
recheck no bug

**Comment by sodar** [comment]
recheck no bug

**Comment by m-kostrzewa** [comment]
@sodar @pmarcinkiewicz1 can we go ahead with this?

**Comment by sodar** [comment]
recheck windows

**Comment by sodar** [comment]
recheck no bug

**Comment by sodar** [comment]
recheck no bug

**Pull request merged**
