### PR TITLE
Rename ScontsTestsLogs to vRouterUnitTestReport

### PR DESCRIPTION
**Pull request by m-kostrzewa**
I feel like the old name is not descriptive enough for folks outside of Windows team.

### CODE REVIEW

**Comment by m-kostrzewa** [comment]
recheck windows

**Comment by m-kostrzewa** [comment]
recheck no bug

**Comment by m-kostrzewa** [comment]
@jablonskim vRouter actually is often refered to by Juniper when talking about vRouter + Agent combo. What do you think then?

**Comment by jablonskim** [comment]
Ok, then it's OK for me

**Comment by m-kostrzewa** [comment]
@jablonskim k

**Pull request closed without merging**
